use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.ms.netease.com/neteaselottery/ldcpspecs.git'
source 'https://git.ms.netease.com/commonlibraryios/podspec.git'

target 'LDCPRLCTableView_Example', :exclusive => true do
    pod "LDCPRLCTableView", :path => "../"
end

target 'LDCPRLCTableView_Tests', :exclusive => true do
    pod "LDCPRLCTableView", :path => "../"
    
    
end